### ISSUE TITLE
[Epic] Add CommandBufferThunk to XLA:GPU

### ISSUE THREAD

**Issue by ezhulenev** [openxla/xla#6242]
Add a mini-interpreter for constructing and updating StreamExecutor command buffers at run time based on XLA:GPU buffer assignment.
```[tasklist]
### Tasks
- [ ] https://github.com/openxla/xla/issues/6243
- [ ] https://github.com/openxla/xla/issues/6935
- [ ] https://github.com/openxla/xla/issues/6936
```
