### ISSUE TITLE
[Epic] StreamExecutor must support CUDA C++ kernels with C++ struct args

### ISSUE THREAD

**Issue by ezhulenev** [openxla/xla#6703]
Today StreamExecutor supports only kernels loaded from PTX into CUmodule and CUfunction, we need to add support for kernels written in CUDA C++ and resolved from a C++ symbol pointer. Long term goal is to be able to load CUTLASS kernels as `se::Kernel`
```[tasklist]
### Tasks
- [ ] https://github.com/openxla/xla/issues/6704
- [ ] https://github.com/openxla/xla/issues/6772
- [ ] https://github.com/openxla/xla/issues/6904
```
